package dataapi

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/net/html"

	"github.com/andybalholm/cascadia"
)

// selector_test.go is the gate's evidence. The gate is the one part of this port with no JavaScript
// counterpart to diff against — it is new code that decides what the port will and will not answer
// — so its correctness rests on a recorded differential rather than on assertions I invented.
//
// testdata/selector-parity.json is generated by scripts/gen-selector-parity.mjs against the same
// cheerio the reference engine uses. Two lists, two opposite claims:
//
//	parity    the gate lets it through, and Go must return EXACTLY cheerio's node set
//	rejected  the gate refuses it, and cheerio's answer is recorded to show what that costs
//
// The rejected list is the more important of the two. Thirty of its entries are selectors cheerio
// answers happily; every one is a deliberate divergence, and having them written down with the
// reference's own output is what keeps "unsupported" from quietly becoming "wrong".

type parityFile struct {
	Fixture string                 `json:"fixture"`
	Cheerio string                 `json:"cheerio"`
	Parity  map[string]parityEntry `json:"parity"`
	Reject  map[string]parityEntry `json:"rejected"`
}

type parityEntry struct {
	OK      bool     `json:"ok"`
	IDs     []string `json:"ids"`
	Error   string   `json:"error"`
	Message string   `json:"message"`
}

func loadParity(t *testing.T) parityFile {
	t.Helper()
	raw, err := os.ReadFile("testdata/selector-parity.json")
	if err != nil {
		t.Fatalf("read parity baseline: %v", err)
	}
	var pf parityFile
	if err := json.Unmarshal(raw, &pf); err != nil {
		t.Fatalf("parity baseline is not valid JSON: %v", err)
	}
	if len(pf.Parity) == 0 || len(pf.Reject) == 0 {
		t.Fatal("parity baseline is empty")
	}
	return pf
}

// nodeID names a node the way the generator did, so the two id lists are directly comparable.
func nodeID(n *html.Node) string {
	if id, ok := attrValue(n, "id"); ok {
		return id
	}
	return "<" + n.Data + ">"
}

// TestSelectorParity is the core claim: for every construct the gate admits, this port returns the
// same nodes, in the same order, as the engine it is a port of.
func TestSelectorParity(t *testing.T) {
	pf := loadParity(t)
	root := doc(t, pf.Fixture)

	for selector, want := range pf.Parity {
		t.Run(selector, func(t *testing.T) {
			if !want.OK {
				t.Fatalf("baseline says cheerio errored (%s); it does not belong in the parity list", want.Error)
			}

			got, err := Find(root.Root, selector, FindOpts{})
			if err != nil {
				t.Fatalf("Find(%q) = %v, but cheerio answered %v", selector, err, want.IDs)
			}

			ids := make([]string, 0, len(got))
			for _, n := range got {
				ids = append(ids, nodeID(n))
			}
			if strings.Join(ids, ",") != strings.Join(want.IDs, ",") {
				t.Errorf("\n got: %v\nwant: %v (cheerio)", ids, want.IDs)
			}
		})
	}
	t.Logf("parity: %d selectors match cheerio exactly", len(pf.Parity))
}

// TestSelectorRejections pins the other half. Every one of these must fail, and fail as a
// SelectorFailure rather than by returning the wrong data — a rejection that leaked through as a
// silent empty result would be indistinguishable from a correct answer at the HTTP layer.
func TestSelectorRejections(t *testing.T) {
	pf := loadParity(t)
	root := doc(t, pf.Fixture)
	var divergent int

	for selector, reference := range pf.Reject {
		t.Run(selector, func(t *testing.T) {
			got, err := Find(root.Root, selector, FindOpts{})
			if err == nil {
				t.Fatalf("Find(%q) succeeded with %d nodes; the gate must refuse it", selector, len(got))
			}
			var fail SelectorFailure
			if !errors.As(err, &fail) {
				t.Fatalf("Find(%q) = %T, want a SelectorFailure: %v", selector, err, err)
			}
			if reference.OK {
				divergent++
			}
		})
	}
	t.Logf("rejections: %d total, %d of which cheerio answers (deliberate divergences)",
		len(pf.Reject), divergent)
}

// TestParityBaselineIsNonVacuous guards the way a recorded baseline rots: if the generator's
// selector list and the corpus drift apart, or someone regenerates against a broken engine, every
// assertion still "passes" against whatever was recorded. These are the properties the file must
// have for the two tests above to mean anything.
func TestParityBaselineIsNonVacuous(t *testing.T) {
	pf := loadParity(t)

	var answered, empty int
	for _, e := range pf.Parity {
		if !e.OK {
			t.Errorf("a parity entry recorded an error; it belongs in the rejected list")
		}
		if len(e.IDs) > 0 {
			answered++
		} else {
			empty++
		}
	}
	// A baseline of all-empty results would pass against almost any implementation.
	if answered < len(pf.Parity)/2 {
		t.Errorf("only %d of %d parity selectors match anything — the baseline proves little",
			answered, len(pf.Parity))
	}
	// ...but some empties are load-bearing (`.row:eq(9)`, `[href='/DOCS']`), so require both kinds.
	if empty == 0 {
		t.Error("no parity selector returns an empty set; the negative cases are missing")
	}

	var divergent int
	for _, e := range pf.Reject {
		if e.OK {
			divergent++
		}
	}
	if divergent == 0 {
		t.Error("no rejected selector is one cheerio answers — the rejections cost nothing, " +
			"which means they are not testing the gate")
	}

	// The two baselines have to describe the same reference. If the conformance corpus is
	// regenerated against a new cheerio and this file is not, "parity" would be measured against
	// one engine and asserted against another, and nothing would say so.
	version, err := os.ReadFile(filepath.Join(corpusDir, "VERSION"))
	if err != nil {
		t.Fatalf("read conformance VERSION: %v", err)
	}
	i := strings.Index(string(version), "{")
	if i < 0 {
		t.Fatal("conformance VERSION has no manifest block")
	}
	var manifest struct {
		Cheerio string `json:"cheerio"`
	}
	if err := json.Unmarshal(version[i:], &manifest); err != nil {
		t.Fatalf("conformance VERSION manifest: %v", err)
	}
	if pf.Cheerio == "" {
		t.Error("the parity baseline records no cheerio version — re-run `make sync-selector-parity`")
	} else if pf.Cheerio != manifest.Cheerio {
		t.Errorf("parity baseline used cheerio %s but the conformance corpus used %s; "+
			"regenerate both from the same checkout", pf.Cheerio, manifest.Cheerio)
	}
}

// TestGateCatchesEscapedAndCasedNames is the scanner's reason to exist, stated as a test. A gate
// that greps the raw selector text for a name list passes everything here.
func TestGateCatchesEscapedAndCasedNames(t *testing.T) {
	root := doc(t, `<ul><li id="l1" class="row">x</li></ul>`)

	for _, selector := range []string{
		`li:matches(.row)`,       // plain
		`li:MATCHES(.row)`,       // upper-cased, which both parsers fold
		`li:\6d atches(.row)`,    // hex escape with the trailing-space terminator
		`li:\6D atches(.row)`,    // upper-case hex
		`li:\6d\61 tches(.row)`,  // two escapes running together
		`li:m\61 tches(.row)`,    // partially escaped
		`li:not(:matches(.row))`, // buried inside an argument the scanner has to recurse into
		`li:not(:not(:matches(.row)))`,
		`li:has(:MATCHES(.row))`,
	} {
		_, err := Find(root.Root, selector, FindOpts{})
		var unsupported *UnsupportedSelector
		if !errors.As(err, &unsupported) {
			t.Errorf("Find(%q) = %v, want the gate to recognise :matches", selector, err)
		}
	}

	// The mirror: an escaped name that IS allowed must still work, or the scanner would be
	// rejecting on the raw text rather than on the decoded name.
	got, err := Find(root.Root, `li:\66 irst`, FindOpts{})
	if err != nil {
		t.Fatalf(`escaped :first should be allowed: %v`, err)
	}
	if len(got) != 1 || nodeID(got[0]) != "l1" {
		t.Errorf("escaped :first = %v, want [l1]", got)
	}
}

// TestPositionalPlacement pins the grammar the plan settled on: one terminal positional per
// top-level comma group. Non-terminal placement is refused rather than approximated, because a
// post-filter can only ever describe the last compound.
func TestPositionalPlacement(t *testing.T) {
	root := doc(t, `<ul id="u"><li id="l1"><b id="b1">x</b></li><li id="l2"><b id="b2">y</b></li></ul>`)

	for _, c := range []struct {
		selector string
		want     []string
	}{
		{"li:first", []string{"l1"}},
		{"li:last", []string{"l2"}},
		{"li:eq(1)", []string{"l2"}},
		{"li:eq(-1)", []string{"l2"}},
		{"li:eq(-3)", nil},
		{"#u li:first, #u b:last", []string{"l1", "b2"}}, // per group, not over the union
		{"b:first, li:first", []string{"l1", "b1"}},      // ...and merged in DOCUMENT order
	} {
		got, err := Find(root.Root, c.selector, FindOpts{})
		if err != nil {
			t.Fatalf("Find(%q): %v", c.selector, err)
		}
		var ids []string
		for _, n := range got {
			ids = append(ids, nodeID(n))
		}
		if strings.Join(ids, ",") != strings.Join(c.want, ",") {
			t.Errorf("Find(%q) = %v, want %v", c.selector, ids, c.want)
		}
	}

	for _, selector := range []string{
		"li:first b", "li:first > b", "li:eq(0) b", "li:contains(x) b", ":checked + b",
		"li:first:last", "li:first:eq(0)", "li:first, li:first b",
	} {
		_, err := Find(root.Root, selector, FindOpts{})
		var unsupported *UnsupportedSelector
		if !errors.As(err, &unsupported) {
			t.Errorf("Find(%q) = %v, want an UnsupportedSelector", selector, err)
		}
	}
}

// TestPeeledResidueKeepsCombinators is the subtle failure the `needStar` branch exists for. Peeling
// ":first" off "li :first" leaves "li ", and a residue that ends in a dangling combinator compiles
// to something with a completely different meaning rather than to an error.
func TestPeeledResidueKeepsCombinators(t *testing.T) {
	root := doc(t, `<div id="d"><b id="b1">x</b><b id="b2">y</b></div><b id="b3">z</b>`)

	for _, c := range []struct {
		selector string
		want     string
	}{
		{"#d :first", "b1"},   // descendant, NOT #d itself
		{"#d > :first", "b1"}, // child combinator left dangling
		{":first", "<html>"},  // the whole document's first element
		{"#d b:first", "b1"},  // attached to a compound: no star needed
	} {
		got, err := Find(root.Root, c.selector, FindOpts{})
		if err != nil {
			t.Fatalf("Find(%q): %v", c.selector, err)
		}
		if len(got) != 1 || nodeID(got[0]) != c.want {
			var ids []string
			for _, n := range got {
				ids = append(ids, nodeID(n))
			}
			t.Errorf("Find(%q) = %v, want [%s]", c.selector, ids, c.want)
		}
	}
}

// TestCheckedMatchesCheerio pins the one pseudo this package reimplements additively. cascadia and
// cheerio agree on every explicit case and differ only on a <select> with no [selected] option,
// where the browser (and cheerio) default to the first one.
func TestCheckedMatchesCheerio(t *testing.T) {
	for _, c := range []struct {
		name string
		html string
		want []string
	}{
		{"implicit first option", `<select><option id="a">a</option><option id="b">b</option></select>`, []string{"a"}},
		{"explicit selected wins", `<select><option id="a">a</option><option id="b" selected>b</option></select>`, []string{"b"}},
		{"multiple has no default", `<select multiple><option id="a">a</option></select>`, nil},
		{"optgroup blocks the default", `<select><optgroup><option id="a">a</option></optgroup></select>`, nil},
		{"option outside a select", `<option id="a">a</option>`, nil},
		{"a selected sibling cancels it", `<select><option id="a">a</option><option id="b" selected>b</option><option id="c">c</option></select>`, []string{"b"}},
		{"input needs a type", `<input id="a" checked>`, nil},
		{"checkbox, case-folded type", `<input id="a" type="CHECKBOX" checked>`, []string{"a"}},
		{"radio", `<input id="a" type="radio" checked>`, []string{"a"}},
		{"unchecked", `<input id="a" type="checkbox">`, nil},
		{"text input", `<input id="a" type="text" checked>`, nil},
		{"leading text node still first-of-type", `<select>  <option id="a">a</option></select>`, []string{"a"}},
	} {
		t.Run(c.name, func(t *testing.T) {
			got, err := Find(doc(t, c.html).Root, ":checked", FindOpts{})
			if err != nil {
				t.Fatal(err)
			}
			var ids []string
			for _, n := range got {
				ids = append(ids, nodeID(n))
			}
			if strings.Join(ids, ",") != strings.Join(c.want, ",") {
				t.Errorf(":checked = %v, want %v", ids, c.want)
			}
		})
	}
}

// TestAdapterFiltersRunAfterPositionals fixes the order of two independent filters. cheerio applies
// the positional first and the caller filters the result, so ".row:first" over a document whose
// first .row is a seed is EMPTY, not "the first row that isn't a seed".
func TestAdapterFiltersRunAfterPositionals(t *testing.T) {
	root := doc(t, `<ul>
<li id="seed" class="row" cms-template>SEED</li>
<li id="real" class="row">REAL</li>
</ul>`)

	got, err := Find(root.Root, ".row:first", FindOpts{})
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Errorf(".row:first = %v, want nothing: the first .row is a seed and :first does not skip it", got)
	}

	got, err = Find(root.Root, ".row:last", FindOpts{})
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 || nodeID(got[0]) != "real" {
		t.Errorf(".row:last = %v, want [real]", got)
	}
}

// TestContainsIsCaseSensitive is worth its own test because it is the divergence most likely to be
// mistaken for a bug: cascadia's :contains folds case, css-select's does not.
func TestContainsIsCaseSensitive(t *testing.T) {
	root := doc(t, `<p id="p1">Hello World</p><p id="p2">hello world</p>`)

	for _, c := range []struct {
		selector string
		want     []string
	}{
		{"p:contains(Hello)", []string{"p1"}},
		{"p:contains(hello)", []string{"p2"}},
		{`p:contains("Hello World")`, []string{"p1"}},
		{"p:contains(o W)", []string{"p1"}},
		{"p:contains(zzz)", nil},
	} {
		got, err := Find(root.Root, c.selector, FindOpts{})
		if err != nil {
			t.Fatalf("Find(%q): %v", c.selector, err)
		}
		var ids []string
		for _, n := range got {
			ids = append(ids, nodeID(n))
		}
		if strings.Join(ids, ",") != strings.Join(c.want, ",") {
			t.Errorf("Find(%q) = %v, want %v", c.selector, ids, c.want)
		}
	}
}

// unclassifiedByte is the closure property's witness. Every byte of an accepted selector must be
// accounted for: inside a pseudo or attribute token, or else one of the plain compound bytes below.
// Anything else is syntax the scanner did not model, and an accepted selector containing one means
// the gate judged text it never read.
//
// The alphabet is measured, not assumed: running this over the 111 accepted parity selectors yields
// exactly whitespace, `,`, the three combinators, `*`, `.`, `#` and identifier bytes. `|` is here
// for the namespace form, which the corpus has no case of.
func unclassifiedByte(selector string) (int, bool) {
	mask := make([]bool, len(selector))
	cover := func(start, end int) {
		for i := start; i < end && i < len(selector); i++ {
			if i >= 0 {
				mask[i] = true
			}
		}
	}
	for _, g := range scanSelector(selector) {
		for _, p := range g.pseudos {
			cover(p.start, p.end)
		}
		for _, a := range g.attrs {
			cover(a.start, a.end)
		}
	}
	for i := 0; i < len(selector); {
		if mask[i] {
			i++
			continue
		}
		c := selector[i]
		// An escape makes whatever follows part of an identifier: `\!` is a type selector for an
		// element named "!", which the scanner models correctly. The first version of this property
		// checked the escaped byte on its own and the fuzzer found `\!` in under a second — a false
		// positive, and a fair demonstration that the property is live.
		if c == '\\' {
			i += escapeLen(selector, i)
			continue
		}
		switch {
		case isCSSSpace(c), c == ',', c == '>', c == '+', c == '~', c == '*', c == '.', c == '#', c == '|':
		case c >= 0x80, c == '-', c == '_':
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9':
		default:
			return i, true
		}
		i++
	}
	return 0, false
}

// FuzzScanSelector asserts two properties. The first is safety: whatever the scanner is handed, it
// must terminate, stay inside the string, and produce tokens whose offsets are usable for splicing.
// A panic or an out-of-range offset here is a crash in a request handler.
//
// The second is CLOSURE, and it is the one that matters. Every bug in the phase-4 review shared a
// single root: the gate assumed "anything the scanner failed to classify, cascadia will reject too",
// which is false by construction, since the two grammars differing is the whole reason this file
// exists. Closure states the obligation directly — if compileSelector accepts a selector, the
// scanner classified every byte of it — so a future grammar gap is a test failure here rather than a
// silent bypass in someone's shipped app. Safety alone could not catch bug 1, 2 or 3.
func FuzzScanSelector(f *testing.F) {
	for _, seed := range []string{
		"div", ".a > .b", `[href="x"]`, `li:not(:matches(.a))`, `a[href*="`, `:\6d atches(x)`,
		`[a="\"]"]`, `:not(`, `::`, `:::`, `[[[`, `]]]`, `:eq(-1)`, `p:contains("a,b")`,
		`a\`, `[a|=b]`, `[a i]`, `,`, `,,`, `a,`, `:has(> b)`, "\x00", "é:first",
		// The closure-shaped seeds: syntax one engine reads and the other does not.
		`p[a!=b]:matches(x)`, `div/*x*/p`, `[a%b]`, `[a%=b]`, `div/*'*/span`, `[id="/*"]`,
		`[]`, `a,,b`, `[a~=""]`, `p:contains( x )`, `[a=b s]`, `ns|div`, `[ns|a=b]`,
	} {
		f.Add(seed)
	}

	// Seed with cascadia's own canonical reprints. This is the one durable idea from the round-trip
	// proposal (see the plan's "round-trip check" section for why the runtime version was dropped):
	// cascadia's String() is a normalizer, so its output is a different spelling of the same
	// selector, and a different spelling is exactly what trips a scanner that models syntax rather
	// than meaning. Free here, where a false refusal is a red test rather than a shipped break.
	for _, s := range []string{
		"li:nth-child(2)", "li:nth-last-of-type(1)", "[data-x=abc i]", "[rel!=nofollow i]",
		"#solo *", "div:has(b)", "[href='/DOCS']", "a[hreflang|=en i]",
	} {
		if parsed, err := cascadia.ParseGroup(s); err == nil {
			f.Add(parsed.String())
		}
	}

	f.Fuzz(func(t *testing.T, selector string) {
		groups := scanSelector(selector)
		if len(groups) == 0 {
			t.Fatal("scanSelector returned no groups; there is always at least one")
		}
		for _, g := range groups {
			if g.start < 0 || g.end > len(selector) || g.start > g.end {
				t.Fatalf("group bounds [%d,%d) outside [0,%d)", g.start, g.end, len(selector))
			}
			for _, p := range g.pseudos {
				if p.start < 0 || p.end > len(selector) || p.start > p.end {
					t.Fatalf("pseudo %q bounds [%d,%d)", p.name, p.start, p.end)
				}
			}
			for _, a := range g.attrs {
				if a.start < 0 || a.end > len(selector) || a.start > a.end {
					t.Fatalf("attr %q bounds [%d,%d)", a.name, a.start, a.end)
				}
				if a.closeAt < a.start || a.closeAt > len(selector) {
					t.Fatalf("attr %q closeAt %d outside [%d,%d]", a.name, a.closeAt, a.start, len(selector))
				}
			}
		}

		// compileSelector must answer, never panic: every input is either a matcher or a typed error.
		if _, err := compileSelector(selector); err != nil {
			var fail SelectorFailure
			if !errors.As(err, &fail) {
				t.Fatalf("compileSelector(%q) = %T, want a SelectorFailure", selector, err)
			}
			return
		}

		// Closure: accepted means fully classified.
		if i, bad := unclassifiedByte(selector); bad {
			t.Fatalf("compileSelector(%q) accepted a selector with unclassified byte %q at offset %d; "+
				"the scanner does not model this syntax, so the gate judged text it never read",
				selector, selector[i], i)
		}
	})
}
